DROP TABLE IF EXISTS question;
DROP TABLE IF EXISTS answer;

CREATE TABLE question (
  id INTEGER PRIMARY KEY UNIQUE,
  question TEXT UNIQUE NOT NULL,
  question_type TEXT NOT NULL,
  currently_active INT DEFAULT 0,
  active_morning INT DEFAULT 0,
  active_evening INT DEFAULT 0,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE answer (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  answer_id INT NOT NULL,
  question_id INT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  answer TEXT
);